server:
  # 服务器的HTTP端口，默认为80
  port: 18851
  servlet:
    # 应用的访问路径
    context-path: /

logging:
  level:
    com.pascalming: info
    org.springframework: warn

# Spring配置
spring:
  application:
    name: pascalming-demo-provider
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: druid,dubbo

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.pascalming.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis-config.xml
